#:schema node_modules/wrangler/config-schema.json
name = "sub-worker"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "7f9d368e68a54015bba5e6a10fec5e40" }
]

[assets]
directory = "./public"
